"""Add message_type to Message model

Revision ID: a121a52a71ca
Revises: 
Create Date: 2025-05-18 16:54:11.522816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a121a52a71ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_invite', schema=None) as batch_op:
        batch_op.drop_column('uses')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=20), server_default='text', nullable=False))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('message_type')

    with op.batch_alter_table('group_invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uses', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
